volumes:
  test_task_db:

services:

  task_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=test_task
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_USER=postgres
    volumes:
      - test_task_db:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'

  app:
    restart: always
    build: .
    ports:
      - '127.0.0.1:8080:8080'
    depends_on:
      - task_db
    environment:
      SPRING_DATASOURCE_URL : 'jdbc:postgresql://task_db:5432/test_task'
      JAVA_OPTS: '-Xmx512m'
